import { Category, Product } from '../models';

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Cuidado Capilar', slug: 'cuidado-capilar' },
  { id: 'cat-2', name: 'Tratamientos', slug: 'tratamientos' },
  { id: 'cat-3', name: 'Peluquerías', slug: 'peluquerias' },
  { id: 'cat-4', name: 'Mayorista', slug: 'mayorista' },
  { id: 'cat-5', name: 'Combos', slug: 'combos' },
];

export const MOCK_PRODUCTS: Product[] = [
  // Particulares (retail)
  {
    id: 'p-1',
    name: 'Shampoo Reparador 300ml',
    slug: 'shampoo-reparador-300ml',
    description:
      'Shampoo de uso diario con keratina y proteínas del trigo. Repara y fortalece el cabello dañado, dejándolo suave y brillante desde la primera aplicación.',
    price: 2800,
    stock: 50,
    categoryId: 'cat-1',
    categoryName: 'Cuidado Capilar',
    saleType: 'retail',
    imageUrl: 'https://placehold.co/400x400/E8D5C4/5C3D2E?text=Shampoo+Reparador',
    isActive: true,
    featured: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p-2',
    name: 'Acondicionador Nutritivo 300ml',
    slug: 'acondicionador-nutritivo-300ml',
    description:
      'Acondicionador con aceite de argán y manteca de karité. Nutre profundamente, reduce el frizz y facilita el peinado. Ideal para cabello seco y dañado.',
    price: 2600,
    stock: 45,
    categoryId: 'cat-1',
    categoryName: 'Cuidado Capilar',
    saleType: 'retail',
    imageUrl: 'https://placehold.co/400x400/D4E8C4/2E5C3D?text=Acondicionador',
    isActive: true,
    featured: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p-3',
    name: 'Máscara Capilar Hidratante',
    slug: 'mascara-capilar-hidratante',
    description:
      'Tratamiento intensivo de hidratación con ácido hialurónico vegetal. Restaura la humedad perdida y aporta suavidad y flexibilidad al cabello.',
    price: 3500,
    stock: 30,
    categoryId: 'cat-2',
    categoryName: 'Tratamientos',
    saleType: 'retail',
    imageUrl: 'https://placehold.co/400x400/C4D4E8/2E3D5C?text=M%C3%A1scara+Capilar',
    isActive: true,
    featured: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p-4',
    name: 'Aceite Capilar Reparador',
    slug: 'aceite-capilar-reparador',
    description:
      'Mezcla premium de aceites de argán, jojoba y rosa mosqueta. Sella las puntas, aporta brillo y protege del calor sin dejar el cabello grasoso.',
    price: 3200,
    stock: 25,
    categoryId: 'cat-2',
    categoryName: 'Tratamientos',
    saleType: 'retail',
    imageUrl: 'https://placehold.co/400x400/E8E4C4/5C572E?text=Aceite+Capilar',
    isActive: true,
    featured: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },

  // Peluquerías (salon)
  {
    id: 'p-5',
    name: 'Pack Profesional Shampoo x6',
    slug: 'pack-profesional-shampoo-x6',
    description:
      'Pack de 6 unidades de Shampoo Reparador 300ml. Ideal para peluquerías y salones de belleza. Precio especial por volumen con entrega express.',
    price: 14400,
    stock: 20,
    categoryId: 'cat-3',
    categoryName: 'Peluquerías',
    saleType: 'salon',
    imageUrl: 'https://placehold.co/400x400/E8C4C4/5C2E2E?text=Pack+x6+Shampoo',
    isActive: true,
    featured: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p-6',
    name: 'Pack Tratamiento Salón x6',
    slug: 'pack-tratamiento-salon-x6',
    description:
      'Pack de 6 unidades de Máscara Capilar Hidratante. Formulado para uso profesional en salones. Resultados visibles desde la primera aplicación.',
    price: 18000,
    stock: 15,
    categoryId: 'cat-3',
    categoryName: 'Peluquerías',
    saleType: 'salon',
    imageUrl: 'https://placehold.co/400x400/C4C4E8/2E2E5C?text=Pack+x6+Tratamiento',
    isActive: true,
    featured: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p-7',
    name: 'Pack Acondicionador Salón x6',
    slug: 'pack-acondicionador-salon-x6',
    description:
      'Pack de 6 unidades de Acondicionador Nutritivo 300ml para uso profesional. Precio exclusivo para peluquerías con descuento aplicado.',
    price: 13200,
    stock: 18,
    categoryId: 'cat-3',
    categoryName: 'Peluquerías',
    saleType: 'salon',
    imageUrl: 'https://placehold.co/400x400/C4E8C4/2E5C2E?text=Pack+x6+Acond',
    isActive: true,
    featured: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },

  // Mayorista (wholesale)
  {
    id: 'p-8',
    name: 'Caja Shampoo x12',
    slug: 'caja-shampoo-x12',
    description:
      'Caja de 12 unidades de Shampoo Reparador 300ml. Precio mayorista exclusivo para revendedores. Incluye material de merchandising.',
    price: 26400,
    stock: 10,
    categoryId: 'cat-4',
    categoryName: 'Mayorista',
    saleType: 'wholesale',
    imageUrl: 'https://placehold.co/400x400/E8D4C4/5C3D2E?text=Caja+x12+Shampoo',
    isActive: true,
    featured: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p-9',
    name: 'Caja Acondicionador x12',
    slug: 'caja-acondicionador-x12',
    description:
      'Caja de 12 unidades de Acondicionador Nutritivo 300ml. Precio mayorista para distribuidores y revendedores con condiciones especiales.',
    price: 24000,
    stock: 8,
    categoryId: 'cat-4',
    categoryName: 'Mayorista',
    saleType: 'wholesale',
    imageUrl: 'https://placehold.co/400x400/D4E8C4/3D5C2E?text=Caja+x12+Acond',
    isActive: true,
    featured: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p-10',
    name: 'Caja Máscara Capilar x12',
    slug: 'caja-mascara-capilar-x12',
    description:
      'Caja de 12 unidades de Máscara Capilar Hidratante. Ideal para revendedores que buscan el mayor margen de ganancia.',
    price: 36000,
    stock: 6,
    categoryId: 'cat-4',
    categoryName: 'Mayorista',
    saleType: 'wholesale',
    imageUrl: 'https://placehold.co/400x400/C4D4E8/2E3D5C?text=Caja+x12+M%C3%A1scara',
    isActive: true,
    featured: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },

  // Combos
  {
    id: 'p-11',
    name: 'Combo Peluquería Inicial',
    slug: 'combo-peluqueria-inicial',
    description:
      'Kit inicial para peluquerías: 3 Shampoo Reparador + 3 Acondicionador Nutritivo + 2 Máscaras Capilares + 1 Aceite Reparador. Todo lo que necesitás para arrancar.',
    price: 22000,
    stock: 12,
    categoryId: 'cat-5',
    categoryName: 'Combos',
    saleType: 'salon',
    imageUrl: 'https://placehold.co/400x400/E8C4E4/5C2E58?text=Combo+Peluquer%C3%ADa',
    isActive: true,
    featured: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p-12',
    name: 'Combo Revendedor Mayorista',
    slug: 'combo-revendedor-mayorista',
    description:
      'Combo completo para empezar a revender: Caja Shampoo x12 + Caja Acondicionador x12 + 6 Máscaras + 6 Aceites. El mejor precio para arrancar tu negocio capilar.',
    price: 68000,
    stock: 5,
    categoryId: 'cat-5',
    categoryName: 'Combos',
    saleType: 'wholesale',
    imageUrl: 'https://placehold.co/400x400/E4E8C4/585C2E?text=Combo+Mayorista',
    isActive: true,
    featured: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];
